
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordp1
spec:
  selector:
    matchLabels:
      app: wordp1
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordp1
        tier: frontend
    spec:
      containers:
      - image: premasaik/wordpress:V1
        name: word-mysql
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim2
---
apiVersion: v1
kind: Service
metadata:
  name: wordp
  labels:
    app: wordp1
spec:
  ports:
    - port: 80
  selector:
    app: wordp1
    tier: frontend
  type: LoadBalancer
